# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: log

  paths:

    - C:\Users\MarizzaMil\ElasticsearchNodeClient\Introduction\*.log
  input_type: log
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]


